version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            choco install -y mingw cmake
      - run:
          name: Build Dolphin Emulator
          command: |
            mkdir build
            cd build
            cmake ..
            mingw32-make
      - store_artifacts:
          path: build
          destination: dolphin-build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
