name: Build Dolphin Emulator

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Visual Studio 2022
      run: |
        choco install visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --add Microsoft.VisualStudio.Component.Git --add Microsoft.VisualStudio.Component.VC.Tools.ARM64" --ignore-package-exit-codes

    - name: Install Windows 11 SDK
      run: |
        choco install windows-sdk-11-version-22h2-all

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build with MSBuild
      run: |
        cd build
        $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\MSBuild.exe"
        & "${msbuildPath}" ../Source/dolphin-emu.sln /p:Configuration=Release /p:Platform=x64
      shell: pwsh
